spring:
  application:
    name: app-redis-cache
  cache:
    # 虽然它会自动去适配已有Cache的依赖，但先后顺序会对Redis使用有影响（JCache -> EhCache -> Redis -> Guava）
    type: REDIS

server:
  port: 8080
  servlet:
    context-path:
    session:
      timeout: 21600
      cookie:
        max-age: 21600

##默认密码为空
redis:
  host: 127.0.0.1
  port: 6379
  timeout: 5000  # 连接超时时间（毫秒）
  database: 0 #默认是索引为0的数据库
  lettuce:
    pool:
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-idle: 8 # 连接池中的最大空闲连接 默认 8
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
